In [1]:
import numpy as np

In [2]:
Datax = np.loadtxt('PSDSData (17_20)_raw.csv',delimiter=',')
Datay = np.loadtxt('push_finish(17_20)_1.csv',delimiter=',')

In [3]:
Datay[34*60:35*60]

array([0., 0., 0., 0., 0., 0., 1., 1., 1., 1., 1., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [30]:
index=(np.where(Datay==1))[0]

In [36]:
index[6]

1526

In [101]:
y = Datay
gap =150
label_index= np.where(y==1)[0]
segments=np.zeros([0,2],dtype=int)
last_seg = 0

for i in range(len(label_index) -1):
    if ((label_index[i+1]-label_index[i])>gap):
        seg = int((label_index[i+1]+label_index[i])/2)
        segments = np.append(segments,[[last_seg,seg]],axis=0)
        last_seg=seg
segments = np.append(segments,[[last_seg,len(Datay)]],axis=0)

In [64]:
np.zeros([1,2])

array([[0., 0.]])

In [68]:
len(Datay)

135131

In [102]:
segments.shape

(55, 2)

In [121]:
def data_shuffle(x,y,gap=150):
    
    label_index= np.where(y==1)[0]
    segments=np.zeros([0,2],dtype=int)
    last_seg = 0

    for i in range(len(label_index) -1):
        if ((label_index[i+1]-label_index[i])>gap):
            seg = int((label_index[i+1]+label_index[i])/2)
            segments = np.append(segments,[[last_seg,seg]],axis=0)
            last_seg=seg
    segments = np.append(segments,[[last_seg,len(Datay)]],axis=0)
    newSeg = np.arange(len(segments))
    np.random.shuffle(newSeg)
    newx = np.zeros([0,Datax.shape[1]])
    newy = np.zeros([0])
    for i in range(len(newSeg)):
        newx = np.append(newx,x[segments[newSeg[i]][0]:segments[newSeg[i]][1]],axis=0)
        newy = np.append(newy,y[segments[newSeg[i]][0]:segments[newSeg[i]][1]],axis=0)
    return newx,newy

In [95]:
newx = np.zeros([0,9])

In [90]:
Datax.shape[1]

9

In [105]:
segments[0]

array([   0, 1952])

In [47]:
segments=data_shuffle(Datax,Datay)

In [107]:
Datay[segments[0][0]:segments[0][1]].shape

(1952,)

In [122]:
newx,newy = data_shuffle(Datax,Datay)

In [127]:
np.savetxt('x_shuffle_test.csv',newx,delimiter=',')
np.savetxt('y_shuffle_test.csv',newy,delimiter=',')

In [125]:
newy.shape

(135131,)

In [126]:
Datay.shape

(135131,)