In [1]:
import keras.backend as K

Using TensorFlow backend.


In [2]:
import numpy as np

In [3]:
text_file = open("./TapData/100HzTapDataValidation/Tapping_PSDSData(24).annotation~", "r")
#text_file = open("./TapData/push20.annotation_", "r")

lines = text_file.readlines()
text_file.close()
print (len(lines))

298


In [4]:
f=100
float(lines[0].split(';')[0])*f

44132.0

In [5]:
push=[]
for i in range(len(lines)):
    push.append([int(float(lines[i].split(';')[0])*f),int(float(lines[i].split(';')[1])*f)])

In [6]:
push = np.asarray(push)

In [7]:
push.shape

(298, 2)

In [8]:
push[1]

array([44156, 44168])

In [16]:
pushTime=np.empty((0))
for i in range(len(push)):
    if (push[i][1]-push[i][0]!=6):
        print(i)
        print(push[i][1]-push[i][0])
    for j in np.arange(push[i][0],push[i][0]+10):
        pushTime = np.append(pushTime,j)


0
12
1
12
2
12
3
12
4
12
5
12
6
12
7
12
8
12
9
12
10
12
11
12
12
12
13
12
14
12
15
12
16
12
17
12
18
12
19
12
20
12
21
12
22
12
23
12
24
12
25
12
26
12
27
12
28
12
29
12
30
12
31
12
32
12
33
12
34
12
35
12
36
12
37
12
38
12
39
12
40
12
41
12
42
12
43
12
44
12
45
12
46
12
47
12
48
12
49
12
50
12
51
12
52
12
53
12
54
12
55
12
56
12
57
12
58
12
59
12
60
12
61
12
62
11
63
12
64
12
65
12
66
12
67
12
68
12
69
12
70
12
71
12
72
12
73
12
74
12
75
12
76
12
77
12
78
12
79
12
80
12
81
12
82
12
83
12
84
12
85
12
86
12
87
12
88
12
89
12
90
12
91
12
92
12
93
12
94
12
95
13
96
12
97
12
98
12
99
12
100
12
101
12
102
12
103
12
104
12
105
12
106
12
107
12
108
13
109
12
110
12
111
12
112
12
113
12
114
12
115
12
116
13
117
13
118
12
119
12
120
12
121
12
122
12
123
12
124
12
125
12
126
12
127
12
128
12
129
12
130
12
131
11
132
12
133
12
134
13
135
12
136
12
137
12
138
12
139
12
140
11
141
12
142
12
143
12
144
12
145
12
146
12
147
11
148
13
149
11
150
12
151
13
152
12
153
12
154
12
155
11
156
13
157
12
158


In [10]:
pushTime.shape

(5960,)

In [11]:
watch_34_raw = np.loadtxt('./TapData/100HzTapDataValidation/PSDSData (24)_raw.csv',delimiter=",")

In [12]:
watch_34_raw.shape

(120088, 9)

In [17]:
watch_y=np.zeros(len(watch_34_raw))
for i in range(len(pushTime)):
    watch_y[int(pushTime[i])]=1

In [29]:
i

2447

In [14]:
watch_y.shape

(120088,)

In [31]:
watch_y.sum()

2424.0

In [32]:
18432.0/12

1536.0

In [33]:
1538*6

9228

In [34]:
watch_y[4200:4260]

array([1., 1., 1., 1., 1., 1., 1., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 1., 1., 1., 1.])

In [18]:
np.savetxt('./TapData/100HzTapDataValidation/Tap(24)_100Hz.csv',watch_y)

In [36]:
def shuffle(data,Y):
    window = 5000
    noActiveWindow=150
    segment=[0]
    for i in range (len(data)):
        if (i>segment[-1]+window):
            if Y[i-noActiveWindow:i+noActiveWindow].sum()==0:
                segment.append(i)
    segment.append(i)
    newOrder = np.arange(len(segment)-1)
    np.random.shuffle(newOrder)
    newData = np.empty_like(data[0:1])
    newY = np.empty_like(Y[0:1])
    for i in range(len(newOrder)):
        newData = np.append(newData,data[segment[newOrder[i]]:segment[newOrder[i]+1]],axis=0)
        newY = np.append(newY,Y[segment[newOrder[i]]:segment[newOrder[i]+1]])
    return newData,newY

In [129]:
newD,newY = shuffle(watch_34_raw,watch_y)

In [132]:
np.savetxt('./TapData/data_100Hz_shuffle.csv',newD,delimiter=",")
np.savetxt('./TapData/data_100Hz_y_shuffle.csv',newY)

In [131]:
newD[0]

array([5.6610107e-03, 3.5247803e-03, 4.9743652e-03, 1.3947606e-02,
       9.3054770e-04, 4.7721863e-03, 1.1463252e+00, 3.2973344e+00,
       9.1642730e+00])

In [127]:
watch_34_raw.shape

(512141, 9)

In [85]:
seg

[0,
 5001,
 10424,
 15425,
 20754,
 26124,
 31125,
 36126,
 41127,
 46328,
 51782,
 56783,
 62562,
 67563,
 72564,
 78604,
 86350,
 95324,
 100325,
 105578,
 110684,
 118228,
 123440,
 128771,
 134312,
 139313,
 144314,
 149315,
 154316,
 159317,
 164318,
 169319,
 174320,
 179321,
 184322,
 189323,
 194324,
 199325,
 204326,
 209327,
 214328,
 219329,
 224330,
 229331,
 234332,
 239333,
 244334,
 249335,
 254336,
 259337,
 264338,
 269339,
 274340,
 279341,
 284342,
 289343,
 294344,
 299345,
 304346,
 309347,
 314348,
 319349,
 324350,
 329351,
 334352,
 339353,
 344354,
 349355,
 354356,
 359357,
 364358,
 369359,
 374360,
 379361,
 384362,
 389363,
 394364,
 399365,
 404366,
 409367,
 414368,
 419369,
 424370,
 429371,
 434372,
 439373,
 444374,
 449375,
 454376,
 461132,
 468490,
 473491,
 478492,
 483622,
 488623,
 493624,
 498625,
 503626,
 508627]

In [58]:
watch_4_29= np.load('watch_4_29.npy')

In [59]:

watch_4_29.shape

(20941, 32, 18)

In [60]:
watch_4_29_raw= np.load('watch_4_29_raw.npy')

In [61]:
watch_4_29_raw.shape

(20972, 9)

In [76]:
watch_4_29_y=np.zeros((len(watch_4_29)))
watch_4_29_y.shape

(20941,)

In [77]:
for i in range(len(pushTime)):
    watch_4_29_y[int(pushTime[i]-31)]=1

In [78]:
np.save('watch_4_29_y.npy',watch_4_29_y)

In [79]:
watch_4_29_y=np.append(np.zeros((31)),watch_4_29_y)
watch_4_29_y.shape

(20972,)

In [80]:
np.savetxt('watch_4_29_y.csv',watch_4_29_y)