In [1]:
import keras.backend as K

Using TensorFlow backend.


In [2]:
import numpy as np

In [3]:
text_file = open("./push_32.annotation~", "r")
#text_file = open("./TapData/push20.annotation_", "r")

lines = text_file.readlines()
text_file.close()
print (len(lines))

1945


In [4]:
f=25
float(lines[0].split(';')[0])*f

6141.0

In [5]:
push=[]
for i in range(len(lines)):
    push.append([int(float(lines[i].split(';')[0])*f),int(float(lines[i].split(';')[1])*f)])

In [6]:
push = np.asarray(push)

In [7]:
push.shape

(1945, 2)

In [8]:
push[1]

array([6177, 6180])

In [9]:
pushTime=np.empty((0))
for i in range(len(push)):
    if (push[i][1]-push[i][0]!=6):
        print(i)
        print(push[i][1]-push[i][0])
    for j in np.arange(push[i][0],push[i][0]+5):
        pushTime = np.append(pushTime,j)


0
3
1
3
2
3
3
3
4
3
5
3
6
2
7
3
8
3
9
3
10
4
11
3
12
3
13
3
14
3
15
3
16
3
17
2
18
3
19
3
20
3
21
3
22
3
23
3
24
2
25
3
26
2
27
2
28
3
29
3
30
3
31
3
32
3
33
3
34
3
35
3
36
3
37
3
38
3
39
3
40
3
41
3
42
3
43
3
44
3
45
3
46
3
47
3
48
3
49
3
50
3
51
3
52
3
53
3
54
3
55
3
56
3
57
3
58
3
59
3
60
3
61
3
62
3
63
3
64
3
65
3
66
3
67
3
68
3
69
3
70
3
71
3
72
3
73
3
74
3
75
3
76
3
77
3
78
3
79
3
80
3
81
3
82
3
83
3
84
3
85
3
86
3
87
3
88
3
89
3
90
3
91
3
92
3
93
3
94
3
95
3
96
3
97
3
98
3
99
3
100
3
101
3
102
3
103
3
104
3
105
3
106
3
107
3
108
3
109
3
110
3
111
3
112
3
113
3
114
3
115
3
116
3
117
3
118
3
119
3
120
2
121
3
122
3
123
4
124
3
125
3
126
3
127
4
128
3
129
3
130
3
131
3
132
3
133
3
134
3
135
3
136
4
137
3
138
3
139
3
140
3
141
3
142
3
143
3
144
3
145
3
146
3
147
3
148
3
149
3
150
4
151
4
152
3
153
4
154
3
155
3
156
3
157
3
158
3
159
3
160
4
161
3
162
3
163
3
164
3
165
3
166
3
167
3
168
3
169
3
170
3
171
3
172
3
173
3
174
3
175
3
176
3
177
3
178
3
179
3
180
3
181
3
182
3
183
3
184
3


1548
3
1549
3
1550
2
1551
3
1552
3
1553
3
1554
2
1555
3
1556
4
1557
3
1558
3
1559
3
1560
3
1561
3
1562
4
1563
3
1564
3
1565
3
1566
3
1567
3
1568
3
1569
3
1570
3
1571
3
1572
3
1573
4
1574
3
1575
3
1576
4
1577
3
1578
3
1579
2
1580
3
1581
3
1582
3
1583
3
1584
4
1585
3
1586
4
1587
3
1588
3
1589
4
1590
4
1591
4
1592
4
1593
3
1594
3
1595
3
1596
3
1597
3
1598
2
1599
3
1600
4
1601
3
1602
3
1603
2
1604
4
1605
3
1606
3
1607
3
1608
3
1609
3
1610
3
1611
2
1612
2
1613
3
1614
3
1615
3
1616
3
1617
3
1618
3
1619
4
1620
2
1621
3
1622
3
1623
3
1624
4
1625
3
1626
3
1627
3
1628
3
1629
3
1630
3
1631
3
1632
3
1633
3
1634
3
1635
2
1636
3
1637
3
1638
3
1639
4
1640
3
1641
4
1642
3
1643
3
1644
3
1645
3
1646
3
1647
2
1648
3
1649
3
1650
3
1651
4
1652
3
1653
3
1654
3
1655
4
1656
3
1657
2
1658
2
1659
2
1660
3
1661
2
1662
3
1663
4
1664
3
1665
3
1666
3
1667
3
1668
3
1669
3
1670
4
1671
3
1672
3
1673
3
1674
2
1675
4
1676
3
1677
3
1678
3
1679
3
1680
3
1681
4
1682
3
1683
4
1684
3
1685
3
1686
4
1687
3
1688
4
1689
3
1690
2

In [10]:
pushTime.shape

(9725,)

In [11]:
watch_34_raw = np.loadtxt('./PSDSData (32)_raw.csv',delimiter=",")

In [12]:
watch_34_raw.shape

(134823, 13)

In [13]:
watch_y=np.zeros(len(watch_34_raw))
for i in range(len(pushTime)):
    watch_y[int(pushTime[i])]=1

In [14]:
i

9724

In [15]:
watch_y.shape

(134823,)

In [16]:
watch_y.sum()

9715.0

In [17]:
18432.0/12

1536.0

In [18]:
1538*6

9228

In [19]:
watch_y[4200:4260]

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [20]:
np.savetxt('./push_32.csv',watch_y)

In [36]:
def shuffle(data,Y):
    window = 5000
    noActiveWindow=150
    segment=[0]
    for i in range (len(data)):
        if (i>segment[-1]+window):
            if Y[i-noActiveWindow:i+noActiveWindow].sum()==0:
                segment.append(i)
    segment.append(i)
    newOrder = np.arange(len(segment)-1)
    np.random.shuffle(newOrder)
    newData = np.empty_like(data[0:1])
    newY = np.empty_like(Y[0:1])
    for i in range(len(newOrder)):
        newData = np.append(newData,data[segment[newOrder[i]]:segment[newOrder[i]+1]],axis=0)
        newY = np.append(newY,Y[segment[newOrder[i]]:segment[newOrder[i]+1]])
    return newData,newY

In [129]:
newD,newY = shuffle(watch_34_raw,watch_y)

In [132]:
np.savetxt('./TapData/data_100Hz_shuffle.csv',newD,delimiter=",")
np.savetxt('./TapData/data_100Hz_y_shuffle.csv',newY)

In [131]:
newD[0]

array([5.6610107e-03, 3.5247803e-03, 4.9743652e-03, 1.3947606e-02,
       9.3054770e-04, 4.7721863e-03, 1.1463252e+00, 3.2973344e+00,
       9.1642730e+00])

In [127]:
watch_34_raw.shape

(512141, 9)

In [85]:
seg

[0,
 5001,
 10424,
 15425,
 20754,
 26124,
 31125,
 36126,
 41127,
 46328,
 51782,
 56783,
 62562,
 67563,
 72564,
 78604,
 86350,
 95324,
 100325,
 105578,
 110684,
 118228,
 123440,
 128771,
 134312,
 139313,
 144314,
 149315,
 154316,
 159317,
 164318,
 169319,
 174320,
 179321,
 184322,
 189323,
 194324,
 199325,
 204326,
 209327,
 214328,
 219329,
 224330,
 229331,
 234332,
 239333,
 244334,
 249335,
 254336,
 259337,
 264338,
 269339,
 274340,
 279341,
 284342,
 289343,
 294344,
 299345,
 304346,
 309347,
 314348,
 319349,
 324350,
 329351,
 334352,
 339353,
 344354,
 349355,
 354356,
 359357,
 364358,
 369359,
 374360,
 379361,
 384362,
 389363,
 394364,
 399365,
 404366,
 409367,
 414368,
 419369,
 424370,
 429371,
 434372,
 439373,
 444374,
 449375,
 454376,
 461132,
 468490,
 473491,
 478492,
 483622,
 488623,
 493624,
 498625,
 503626,
 508627]

In [58]:
watch_4_29= np.load('watch_4_29.npy')

In [59]:

watch_4_29.shape

(20941, 32, 18)

In [60]:
watch_4_29_raw= np.load('watch_4_29_raw.npy')

In [61]:
watch_4_29_raw.shape

(20972, 9)

In [76]:
watch_4_29_y=np.zeros((len(watch_4_29)))
watch_4_29_y.shape

(20941,)

In [77]:
for i in range(len(pushTime)):
    watch_4_29_y[int(pushTime[i]-31)]=1

In [78]:
np.save('watch_4_29_y.npy',watch_4_29_y)

In [79]:
watch_4_29_y=np.append(np.zeros((31)),watch_4_29_y)
watch_4_29_y.shape

(20972,)

In [80]:
np.savetxt('watch_4_29_y.csv',watch_4_29_y)